version: '3'

services:
  mongodb:
    image: mongo:7.0-rc-jammy
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example_password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  myapp:
    build:
      context: ./
    container_name: mongo-mock-writer
    environment:
      - MONGO_URI=mongodb://root:example_password@mongodb:27017/
    depends_on:
      - mongodb

volumes:
  mongodb_data:
